"""ARGOSearchTools: pgvector cosine similarity search over tool_registry.

The component takes a query embedding (already generated by an upstream
embedding model) plus the agent_id, and returns the top-k matching tools
that the agent has permission to use.
"""

from __future__ import annotations

from typing import Any

from langflow.custom import Component
from langflow.io import DataInput, IntInput, Output
from langflow.schema import Data

from _argo_db import call_function_all, vector_literal


class ARGOSearchTools(Component):
    display_name = "ARGO Search Tools"
    description = (
        "Semantic tool search via pgvector. Returns top-k tools the given "
        "agent is permitted to use, ordered by cosine similarity."
    )
    icon = "search"
    name = "ARGOSearchTools"

    inputs = [
        DataInput(
            name="query_embedding",
            display_name="Query Embedding",
            info="List[float] embedding of the user query.",
            required=True,
        ),
        IntInput(
            name="agent_id",
            display_name="Agent ID",
            info="ARGO agent_id requesting the tools.",
            required=True,
        ),
        IntInput(
            name="top_k",
            display_name="Top K",
            info="Number of tools to return.",
            value=5,
            required=False,
        ),
    ]

    outputs = [
        Output(
            name="tools",
            display_name="Tools",
            method="search",
        ),
    ]

    def search(self) -> Data:
        embedding = self._extract_embedding(self.query_embedding)
        if embedding is None:
            raise ValueError("ARGOSearchTools: 'query_embedding' must be a list of floats.")

        try:
            agent_id = int(self.agent_id)
        except (TypeError, ValueError) as exc:
            raise ValueError("ARGOSearchTools: 'agent_id' must be an integer.") from exc

        top_k = int(self.top_k or 5)

        rows = call_function_all(
            "SELECT * FROM argo_public.fn_search_tools(%s::vector, %s, %s)",
            (vector_literal(embedding), agent_id, top_k),
        )

        self.status = f"{len(rows)} tools matched"
        return Data(data={"tools": rows, "agent_id": agent_id})

    @staticmethod
    def _extract_embedding(value: Any) -> list[float] | None:
        if value is None:
            return None
        if hasattr(value, "data"):
            value = value.data
        if isinstance(value, dict):
            value = value.get("embedding") or value.get("vector") or value.get("data")
        if isinstance(value, list) and value and isinstance(value[0], (int, float)):
            return [float(x) for x in value]
        return None